version: '3.3'

services:
  ui:
    image: ghcr.io/multimoml/ui:latest
    container_name: ui
    restart: unless-stopped
    networks:
      - traefik-proxy
    environment:
     PUBLIC_SPEECHLY_APPID: ${PUBLIC_SPEECHLY_APPID} # does not work
    labels:
      traefik.enable: true
      traefik.http.routers.ui.entrypoints: https
      traefik.http.routers.ui.rule: Host(`multimo.ml`)
      traefik.http.services.ui.loadbalancer.server.port: 3000

networks:
  traefik-proxy:
    external: true