version: '1.0'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --api=true
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.email:$ACME_EMAIL
      - --certificatesresolvers.letsencrypt.acme.storage:/opt/traefik/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpChallenge.entryPoint:web
      - --log.level=ERROR
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /opt/traefik/acme.json:/opt/traefik/acme.json
    ports:
      - 80:80
      - 443:443
      # The Web UI
      - "8080:8080"
    restart: always
    networks:
      - web
    labels:
      # Redirect all HTTP to HTTPS permanently
      - traefik.http.routers.http_catchall.rule=HostRegexp(`{any:.+}`)
      - traefik.http.routers.http_catchall.entrypoints=web
      - traefik.http.routers.http_catchall.middlewares=https_redirect
      - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true

  ui:
    image: ghcr.io/rsocena/ui:main
    container_name: ui
    #environment:
    #  - SERVER_KEY_PATH=./private/key.pem
    #  - SERVER_CERT_PATH=./private/cert.pem
    #volumes:
    #  - /path/to/appdata/config:/config
    #ports:
    #   - 3000:3000
    restart: always
    networks:
      - web
    depends_on:
      - traefik
    labels:
      - traefik.http.routers.ui.rule=Host('multimo.ml') #sets the rule for the router
      - traefik.http.routers.ui.tls=true #sets the service to use TLS
      - traefik.http.routers.ui.tls.certresolver=letsEncrypt #references our certificatesResolvers in traefik.yml
      - traefik.http.routers.ui.tls.domains[0].main=multimo.ml #optionally restrict domain


networks:
  web:
    external: true