version: '3.3'

services:
  ui:
    image: ghcr.io/rsocena/ui:main
    container_name: ui
    environment:
      - SERVER_KEY_PATH=/usr/src/app/key.pem
      - SERVER_CERT_PATH=/usr/src/app/cert.pem
    volumes:
      - ./key.pem:/usr/src/app/key.pem
      - ./cert.pem:/usr/src/app/cert.pem
    ports:
       - 443:3000
    restart: always
