version: '3.3'

services:
  ui:
    image: multimoml/ui:latest # ghcr.io/
    container_name: ui
    restart: unless-stopped
    networks:
      - traefik-proxy
    environment:
     PUBLIC_SPEECHLY_APPID: ${PUBLIC_SPEECHLY_APPID}
    labels:
      traefik.enable: true
      traefik.http.routers.ui.entrypoints: https
      traefik.http.routers.ui.rule: Host(`${DOMAIN}`)
      traefik.http.services.ui.loadbalancer.server.port: 3000

networks:
  traefik-proxy:
    external: true