apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: ghcr.io/multimoml/ui:latest
        ports:
        - containerPort: 3000
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: server
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: server
          initialDelaySeconds: 10
          periodSeconds: 3
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 50
      terminationGracePeriodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: server
  selector:
    app: ui

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ui
  namespace: default

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`multimo.ml`)
      kind: Rule
      services:
        - name: ui
          port: 3000
