name: Build and deploy Docker image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    if: "contains(github.event.head_commit.message, '!build!')"
    name: Build and push image to Github registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  deploy:
    if: "contains(github.event.head_commit.message, '!deploy!')"
    runs-on: ubuntu-latest

    steps:
      - name: Wait for result of previus job if any
        if: ${{ needs.build-and-push-image.result }}

      - uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: /home/${{ secrets.SSH_USERNAME }}/deployments/ui

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          docker_login_password: ${{ secrets.GITHUB_TOKEN }}
          docker_login_user: ${{ github.actor }}
          docker_login_registry : ${{ env.REGISTRY }}

          script: |
            echo $docker_login_password | docker login $docker_login_registry -u $docker_login_user --password-stdin
            cd deployments/ui/
            docker-compose up -d --quiet-pull
            docker logout
      